# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.7
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: riyanarhm28@gmail.com
author_name: riyqnn
contract_name: tawf_sharia
deployment_language: python
preset_name: starter
project_name: tawf_sharia

